archive/deploy-analysis.yml

forgot to include the deployment ansible script in the last merge!

oops missed out the deployment yaml

---

analysis/fireballAnalyser.ps1
archive/.bashrc
archive/analysis/addRMSShowerDets.sh
archive/analysis/findAllMatches.sh
archive/analysis/monthlyReports.sh
archive/analysis/stationReports.sh
archive/deploy-site.yml
archive/lambdas/consolidateJpgs.py
archive/lambdas/consolidateLatest.py
archive/lambdas/dailyReport.py
archive/lambdas/deploy_lambdas.ps1
archive/lambdas/ftpfileTrigger.py
archive/website/cameraStatusReport.sh
archive/website/createLatestTable.sh
archive/website/createReportIndex.sh
archive/website/createStationList.sh
archive/website/createSummaryTable.sh
archive/website/static_content/latest/index.html
archive/website/static_content/privacy_data.html
archive/website/static_content/templates/copyright.html
archive/website/static_content/templates/navbar.html
ukmon_pylib/converters/RMStoUFOA.py
ukmon_pylib/fileformats/UAFormats.py
ukmon_pylib/metrics/getMetrics.py
ukmon_pylib/reports/createAnnualBarChart.py
ukmon_pylib/reports/createSearchableFormat.py
ukmon_pylib/utils/plotCAMSOrbits.py

* add privacy statement to website
* creating new station status report
* performance improvements in daily data consolidation
* bugfixes in annual bar-chart 
* moving last remaining generated data into the DATADIR area
* changes to support uploads of manual reduction data
* add file to plot orbits from CAMS SummaryOrbitLog file
* small bugfixes

Bugfixes and improvements

---

.gitignore
analysis/fireballAnalyser.ps1
analysis/makePPallFromPP.ps1
analysis/uploadImprovedFBFiles.ps1
archive/analysis/findAllMatches.sh
archive/analysis/showerReport.sh
archive/cronjobs/nightlyJob.sh
ukmon_pylib/requirements.txt
ukmon_pylib/share/maps/images.json

* upload manually reduced ftpdetect and ecsv files closes #43  
* upload manually solved fireball closes #44 
* Update webpages as needed

Local analysis improvements

---

archive/analysis/createDensityPlots.sh
archive/cronjobs/nightlyJob.sh
archive/static_content/index.html
ukmon_pylib/share/maps/images.json
ukmon_pylib/utils/plotStationsOnMap.py

High level map, will be updated manually as i onboard new stations. Closes #61

Add density plots and station location map

---

analysis/fireballAnalyser.ps1
analysis/uploadImprovedFBFiles.ps1
analysis/uploadOrbit.ps1
archive/analysis/findAllMatches.sh
archive/cronjobs/nightlyJob.sh
archive/lambdas/simplefunctions/dailyReport.py
ukmon_pylib/reports/createExchangeFiles.py
ukmon_pylib/reports/reportOfLatestMatches.py
ukmon_pylib/traj/extraDataFiles.py

Fixes #77 bug in onscreen daily events list
Fixes #75 daily report does not run correctly if rerun or executes after midnight#77

Various bugfixes

---

archive/website/createSummaryTable.sh

Make sure geos_c in the libpath

---

analysis/getFireballFiles.ps1
analysis/uploadImprovedFTP.ps1
analysis/uploadOrbit.ps1
archive/cronjobs/nightlyJob.sh
archive/lambdas/simplefunctions/ftpfileTrigger.py
archive/website/createFireballPage.sh
ukmon_pylib/metrics/camMetrics.py
ukmon_pylib/reports/findFireballs.py
ukmon_pylib/reports/reportBadCameras.py

Create fireball pages for previous years; closes #82 
Track camera upload times using dynamodb table; closes #80 
Notify camera owners about uploads 3 days and 10 days late. Closes #59 
Notify camera owners about uploads with > 500 events. Closes #59 
Various fixes to scripts for local analysis on windows. Mostly used only by me!

Various small fixes and improvements

---

archive/cronjobs/nightlyJob.sh

bugfix in quarterly livedata collection

---

.gitignore
analysis/uploadImprovedFBFiles.ps1
analysis/uploadImprovedFTP.ps1
archive/static_content/browse/apis.html
archive/terraform/mjmm/aws.tf
archive/terraform/mjmm/ec2.tf
archive/terraform/mjmm/iam.tf
archive/terraform/mjmm/s3.tf
archive/terraform/mjmm/variables.tf
ukmon_pylib/converters/RMStoUKMON.py
ukmon_pylib/converters/ftpToECSV.py
ukmon_pylib/utils/drawFTPfile.py

* add terraform to create resources in MJMM account
* bugfixes in local analysis scripts (uploadImprovedFTP and uploadFireball)

Merging a few bugfixes and the new terraform

---

.gitignore
archive/analysis/consolidateOutput.sh
archive/analysis/findAllMatches.sh
archive/cronjobs/getImoWSfile.sh
archive/lambdas/simplefunctions/ftpfileTrigger.py
archive/static_content/browse/apis.html
archive/static_content/index.html
archive/static_content/latest/coverage-maps.html
archive/website/createStationList.sh
ukmon_pylib/fileformats/CameraDetails.py
ukmon_pylib/reports/reportBadCameras.py
ukmon_pylib/traj/extraDataFiles.py
ukmon_pylib/utils/getShowerDates.py
ukmon_pylib/utils/retrieveECSV.py

* Add Detections API 
* performance improvements
* add ftpdetect name to "too many" email - closes #93 
* Started adding terraform code to build infra assets
* improve camera coverage maps

Various fixes and improvements

---

archive/analysis/showerReport.sh
archive/cronjobs/nightlyJob.sh
archive/lambdas/simplefunctions/consolidateJpgs.py
ukmon_pylib/reports/findFireballs.py
ukmon_pylib/traj/extraDataFiles.py

* bug in best-ten picker closes #96 
* copy all mp4s to the archive, to support faster website updates

Bugfixes and performance improvements

---

archive/analysis/addRMSShowerDets.sh
archive/analysis/getRMSSingleData.sh
archive/analysis/showerReport.sh
archive/cronjobs/nightlyJob.sh
archive/utils/monthlyCleardown.sh
ukmon_pylib/reports/extractors.py
ukmon_pylib/reports/reportBadCameras.py

* Simplication and removal of unused code closes #106 
* bugfixes in a couple of scripts
* consider everything brighter than mag -3.7 a fireball

Merging bugfixes and enhancements

---

archive/website/createSummaryTable.sh
archive/website/templates/frontpage.html

Improved front page that shows camera count, closes #110 
Security fix in javascript, closes #109

improved front page

---

analysis/fireballAnalyser.ps1
analysis/manualReduction.ps1
analysis/uploadOrbit.ps1
archive/cronjobs/nightlyJob.sh
archive/lambdas/samfunctions/getExtraFilesV3/pythoncode/getExtraFiles.py
archive/lambdas/samfunctions/getExtraFilesV3/pythoncode/pickleAnalysis.py
archive/lambdas/samfunctions/getExtraFilesV3/testEvent.json
ukmon_pylib/reports/findFireballs.py
ukmon_pylib/requirements.txt
ukmon_pylib/traj/pickleAnalyser.py
ukmon_pylib/utils/getNextBatchStart.py

* correct error in best abs mag calc; closes #138 
* schedule batch to start at dawn +2hrs ; closes #139 
* Improve local fireball analysis routines 
* bugfix : push .lst files to ukmon-shared for fireball analysis

Bugfixes and enhancements

---

.gitignore
archive/.bash_aliases
archive/.bashrc
archive/analysis/findAllMatches.sh
archive/analysis/runDistrib.sh
archive/containers/trajsolver/trajsolver.py
archive/setup/yum-installs.sh
ukmon_pylib/reports/reportOfLatestMatches.py
ukmon_pylib/traj/clusdetails.txt
ukmon_pylib/traj/consolidateDistTraj.py
ukmon_pylib/traj/createDistribMatchingSh.py
ukmon_pylib/traj/distributeCandidates.py
ukmon_pylib/traj/taskrunner.json
ukmon_pylib/utils/getMatchStats.py
ukmon_pylib/utils/plotStationsOnMap.py
ukmon_pylib/utils/rerunFailedGetExtraFiles.py

* new scripts to create and run the distributed processing model
* changes to findAllMatches to use the distributed model
* small improvements in the container's python code
* additional libraries deployed to calc server to allow latest WMPL distro to be installed
* changes to reporting to support distributed processing
* bugfixes in the code to reprocess failed ExtraFiles and plot stations on a map

Merging in commits to support distributed processing 

---

archive/containers/trajsolvertest/Dockerfile
live/ukmonLivePublisher/package-lock.json
live/ukmonLivePublisher/package.json

kinda hoping that npm knows what its doing!

Adding some patchesto the ukmonlive java

---

archive/website/createLatestTable.sh
ukmon_pylib/fileformats/CameraDetails.py
ukmon_pylib/reports/createLatestTable.py

White - ok
Orange - not recieved for 3+days
Red - not recieved for 10+ days
Note that formally inactive cameras are no longer shown.

Adding colour to the status report background

---

archive/cronjobs/nightlyJob.sh
archive/lambdas/deploy_lambdas.ps1
archive/lambdas/getExtraFilesV2/pythoncode/pickleAnalysis.py
archive/share/majorminor.py
archive/shwrinfo/AUR.txt
ukmon_pylib/fileformats/CameraDetails.py
ukmon_pylib/traj/pickleAnalyser.py

* crash when orbit not calculable #194 
* add IAU link to webpages #193
* create json of camera locations
* file ownership bugfix
* add Aurigids to the list of reported showers

Multiple Bugfixes and small updates

---

.vscode/c_cpp_properties.json
analysis/multiTrackStack.ps1
archive/lambdas/fetchECSV/fetchECSV.py
archive/lambdas/fetchECSV/ftpDetectInfo.py
archive/static_content/about.html
archive/static_content/browse/annual/index.html
archive/static_content/browse/apis.html
archive/static_content/browse/daily/index.html
archive/static_content/browse/index.html
archive/static_content/browse/monthly/index.html
archive/static_content/latest/index.html
archive/static_content/privacy_data.html
archive/static_content/search/index.html
archive/terraform/ee/acm_certs.tf
archive/terraform/ee/files/csvTrigger/csvTrigger.py
archive/terraform/ee/route53.tf
archive/website/createMthlyExtracts.sh
archive/website/templates/coverage-maps.html
archive/website/templates/fbreportindex.html
archive/website/templates/frontpage.html
archive/website/templates/header.html
archive/website/templates/reportindex.html
archive/website/templates/shwrcsvindex.html
archive/website/templates/statreportindex.html
ukmon_pylib/reports/extractors.py
ukmon_pylib/utils/multiTrackStack.py
usermgmt/server/deploy-server.yml
usermgmt/server/jsonToKeyFile.py
usermgmt/server/ukmon.ini
usermgmt/server/update_keyfile.sh

Closes #201 by adding shower to single-station downloads
adds DNS support for the APIs so i can use a custom domain name api.ukmeteornetwork.co.uk
simplifies processing of the ftpdetect files.

Add shower to single-station download

---

archive/website/templates/coverage-maps.html
ukmon_pylib/usertools/findNearDuplicates.py
ukmon_pylib/usertools/getLiveImages.py

* add extra station to the coverage map closes #234
* add function to find duplicates
* improve the code i use to download data from ukmonlive

Small fixes and enhancements

---

ukmon_pylib/converters/tests/20230218_051312-original.kml
ukmon_pylib/converters/tests/tester.ps1
ukmon_pylib/converters/toKML.py

closes #241 and adds a test case

closes Create 3d kml file #241

---

archive/samfunctions/getExtraFilesForEE/pythoncode/pickleAnalysis.py
archive/samfunctions/getExtraFilesV2/pythoncode/pickleAnalysis.py
archive/terraform/ee/dailyReportLambda.tf
archive/terraform/ee/ukmonlive_bucket.tf
archive/terraform/ee/ukmonshared_bucket.tf
archive/terraform/ukmda/copylive_lambda.tf
archive/terraform/ukmda/files/copyLive/copyLive.py
archive/terraform/ukmda/ukmda-live-triggers.tf
archive/ukmon_pylib/maintenance/checkUploadTimes.py
archive/ukmon_pylib/metrics/costMetrics.py
archive/ukmon_pylib/traj/distributeCandidates.py
archive/utils/dataSync.sh
archive/utils/fixMissingOrbits.sh

bugfixes
crash in getextrafiles - closes #278 
crash in distributecandidates - closes #279 
data purge - closes #280

Various bugfixes and enhancements

---

archive/analysis/onlyConsolDistrib.sh
archive/samfunctions/fetchECSV/fetchECSV.py
archive/samfunctions/fetchECSV/template.yml
archive/samfunctions/fireballApi/getFireballFiles.py
archive/samfunctions/fireballApi/template.yml
archive/samfunctions/searchArchive/searchArchive.py
archive/terraform/ee/files/matchDataApi/matchDataApiHandler.py
archive/terraform/ukmda/files/matchApiJson/ukmdaMatchApi.json
archive/terraform/ukmda/files/matchDataApi/matchDataApiHandler.py
archive/ukmon_pylib/traj/distributeCandidates.py

* #287 
* #286  
* #288 
* #289

Bugfixes and small enhancements in APIs and matching engine

---

archive/cronjobs/gatherMonthlyVideos.sh
archive/terraform/ukmda/files/matchApiJson/ukmdaMatchApi.json
archive/terraform/ukmda/matchApiLambda.tf

Enhancement for video gathering

---

archive/analysis/getRMSSingleData.sh
archive/containers/trajsolver/update_wmpl.sh
archive/static_content/css/dragontail.css
archive/static_content/live/index.html
archive/static_content/search/index.html
archive/terraform/README.md
archive/terraform/ukmda/files/policies/ukmda-calcserverpolicy.json
archive/terraform/ukmda/ses.tf
archive/ukmon_pylib/maintenance/recreateOrbitPages.py
archive/ukmon_pylib/reports/findFireballs.py
archive/ukmon_pylib/traj/createDistribMatchingSh.py
archive/ukmon_pylib/traj/pickleAnalyser.py
archive/utils/calcserver/clearSpace.sh
archive/utils/ses-msg-templ.json
archive/utils/statsToMqtt.sh
archive/website/costReport.sh
archive/website/templates/searchdialog-prod.js
usermgmt/deploy-local.yml
usermgmt/deploy-server.yml
usermgmt/dev-vars.yml
usermgmt/prod-vars.yml
usermgmt/windows/stationMaint2.py
usermgmt/windows/testkeys.py

Enh: Remove any remaining mentions of old account / buckets #325 
Enh: Silence various noisy processes
Bugfix: ensure single-data file is created properly 
Bugfix: Fix colours in the datepickers on the seaarch and livestream pages #327 
Bugfix: Fireball page image was broken for new fireballs solved by others #334 
Enh: improve backup and data cleardown processes #333

Bugfixes and tidy up post deletion of ukmon-shared

---

archive/analysis/getLogData.sh
archive/analysis/getRMSSingleData.sh
archive/analysis/runDistrib.sh
archive/cronjobs/nightlyJob.sh
archive/deployment/analysis.yml
archive/terraform/ukmda/ec2.tf
archive/terraform/ukmda/variables.tf
archive/ukmon_pylib/metrics/costMetrics.py
archive/ukmon_pylib/metrics/timingMetrics.py
archive/ukmon_pylib/traj/jsonDbMaintenance.py
archive/utils/clearSpace.sh
archive/utils/getCostMetrics.sh

Various 2024 december updates
- fix to timing metrics graph
- archive the json database to impove performance
- add a new calcserver running Ubuntu - need to cut over in Jan
- remove some redundant code
- start tracking "unused" detections.

December 2024 updates

---

usermgmt/windows/stationMaint2.py

Bugfix for #396, creating wrong folders at startup

Bugfix to user maintenance
